### ISSUE TITLE
concurrent write to websocket connection

### ISSUE THREAD

**Issue by 0xp3p3** [heroku-examples/go-websocket-chat-demo#3]
```
func (rr *redisReceiver) broadcast(data []byte) {
	rr.mu.Lock()
	defer rr.mu.Unlock()
	for id, conn := range rr.conns {
		if err := conn.WriteMessage(websocket.TextMessage, data); err != nil {
			log.WithFields(logrus.Fields{
				"id":   id,
				"data": data,
				"err":  err,
				"conn": conn,
			}).Error("Error writting data to connection! Closing and removing Connection")
			rr.deRegister(id)
		}
	}
}
```

I am using your sample. it is cool, but i am getting "concurrent write to websocket connection" in this part some times
What is it wrong?

**Comment by freeformz** [comment]
Hmm, not sure. I'll have to play around. The entire function is wrapped in a mutex, so it's guaranteed to be synchronous. The reason for the mutex is so that rr.conns (a slice) isn't modified by new connections while broadcasting a message and so that only a single concurrent write is happening on any connection at a given time (https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency).

**Comment by freeformz** [comment]
Does anything particular cause this error (i.e. how can I reproduce?)?

**Comment by jrep2** [comment]
Need to wrap all calls including [this one](https://github.com/heroku-examples/go-websocket-chat-demo/blob/f9251d99ef11319f95b0d1575326849819df615d/chat.go#L85).

**Comment by freeformz** [comment]
@jrep2 At that point the conn is no longer in the rr.conns list, so a broadcast() won't try to write to it.  This is done in the deRegister [line](https://github.com/heroku-examples/go-websocket-chat-demo/blob/f9251d99ef11319f95b0d1575326849819df615d/chat.go#L83) above the one you link to, which takes the same lock as broadcast.

**Comment by jrep2** [comment]
Given that deRegister takes the same lock as broadcast, [this call](https://github.com/heroku-examples/go-websocket-chat-demo/blob/f9251d99ef11319f95b0d1575326849819df615d/redis.go#L111) to `deRegister` from `broadcast` will permanently block the calling thread.

There is no code to `Receive` from this [`Send`](https://github.com/heroku-examples/go-websocket-chat-demo/blob/f9251d99ef11319f95b0d1575326849819df615d/redis.go#L166).  I don't know what happens when the unread data backs up, but it's probably not desirable.  Perhaps call `Do` instead of `Send`/`Flush`.

**Comment by freeformz** [comment]
@jrep2 I pushed a change that removes the mutex altogether: a88cf1b0119d4202f8256d5f1d9ca1abd23fd2ef

That should fix the problem if it was related to locking.

If this problem persists please re-open.
Thanks.
